[package]
name = "example-rquickjs-android"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = "~0.9"

[target.'cfg(target_os = "android")'.dependencies]
rquickjs = { version = "~0.9", features = ["bindgen"] }
