name: Build

permissions:
  contents: read

on:
  push:
    branch:
      - master

env:
  CARGO_TERM_COLOR: always
  ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.2.12479018
  # https://github.com/actions/runner-images/blob/ubuntu24/20250302.1/images/ubuntu/Ubuntu2404-Readme.md

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build arm64
        run: |
          rustup target add aarch64-linux-android
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          export CARGO_LINKER=$CC
          export CLANG_PATH=$CC
          echo $CC && echo $CXX && echo $AR && echo $CARGO_LINKER && echo $CLANG_PATH
          cargo build --target aarch64-linux-android --release -vv
        env:
          RUST_BACKTRACE: full

      - name: Build arm32
        run: |
          rustup target add armv7-linux-androideabi
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang++
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          export CARGO_LINKER=$CC
          export CLANG_PATH=$CC
          echo $CC && echo $CXX && echo $AR && echo $CARGO_LINKER && echo $CLANG_PATH
          cargo build --target armv7-linux-androideabi --release -vv
        env:
          RUST_BACKTRACE: full

      - name: Build x86_64
        run: |
          rustup target add x86_64-linux-android
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang++
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          export CARGO_LINKER=$CC
          export CLANG_PATH=$CC
          echo $CC && echo $CXX && echo $AR && echo $CARGO_LINKER && echo $CLANG_PATH
          cargo build --target x86_64-linux-android --release -vv
        env:
          RUST_BACKTRACE: full

      - name: Build x86_32
        run: |
          rustup target add i686-linux-android
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android30-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android30-clang++
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          export CARGO_LINKER=$CC
          export CLANG_PATH=$CC
          echo $CC && echo $CXX && echo $AR && echo $CARGO_LINKER && echo $CLANG_PATH
          cargo build --target i686-linux-android --release -vv
        env:
          RUST_BACKTRACE: full
