name: Build Release

permissions:
  contents: read

on:
  push:
    branch:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Install libc6 # ensure <bits/libc-header-start.h> exists.
        run: |
          sudo apt update
          sudo apt install libc6-dev

      - name: Find header
        run: sudo find / -name "libc-header-start.h"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check rust version
        run: rustup --version

      - name: Install target
        run: rustup target add aarch64-linux-android # armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Build arm64
        run: cargo build --target aarch64-linux-android --release -vv
        env:
          RUST_BACKTRACE: 1
          CC: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
          CXX: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
          AR: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
