name: Build

permissions:
  contents: read

on:
  push:
    branch:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Install target
        run: rustup target add aarch64-linux-android # armv7-linux-androideabi x86_64-linux-android i686-linux-android

#      - name: Setup android
#        uses: android-actions/setup-android@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup env
        shell: bash
        run: |
          echo "CLANG_PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" >> $GITHUB_ENV
          echo "CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" >> $GITHUB_ENV
          echo "CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++" >> $GITHUB_ENV
          echo "AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV

      - name: Build arm64
        run: cargo build --target aarch64-linux-android --release -vv
        env:
          RUST_BACKTRACE: full
